// 150 questions across 5 assessments (30 each)

export interface QuizQuestion {
  question: string;
  options: string[];
  answer: number;
  topic: string;
}

const ASSESSMENT_1: QuizQuestion[] = [
  { question: "Which phase converts source code into tokens?", options: ["Syntax", "Semantic", "Lexical", "Optimization"], answer: 2, topic: "Lexical Analysis" },
  { question: "Which data structure is used in syntax analysis?", options: ["Stack", "Queue", "Linked List", "Tree"], answer: 3, topic: "Syntax Analysis" },
  { question: "FIRST and FOLLOW sets are used in?", options: ["Lexical Analysis", "LL(1) Parsing", "Optimization", "Code Generation"], answer: 1, topic: "FIRST and FOLLOW" },
  { question: "Three address code is generated in?", options: ["Semantic Analysis", "IR Generation", "Optimization", "Loader"], answer: 1, topic: "Intermediate Code" },
  { question: "Constant folding is an example of?", options: ["Lexical Optimization", "Code Optimization", "Semantic Analysis", "Parsing"], answer: 1, topic: "Code Optimization" },
  { question: "A DFA is used in?", options: ["Syntax Analysis", "Lexical Analysis", "Code Generation", "Linking"], answer: 1, topic: "Finite Automata" },
  { question: "Shift Reduce parser is a type of?", options: ["Top Down Parser", "Bottom Up Parser", "Recursive Parser", "Optimizer"], answer: 1, topic: "Shift Reduce Parser" },
  { question: "Context Free Grammar is used in?", options: ["Syntax Analysis", "Lexical Analysis", "Optimization", "Loader"], answer: 0, topic: "CFG" },
  { question: "Peephole optimization works on?", options: ["Large loops", "Small code segments", "Whole program", "Grammar rules"], answer: 1, topic: "Peephole Optimization" },
  { question: "DAG is used for?", options: ["Tokenizing", "Parse tree", "Optimization", "Linking"], answer: 2, topic: "DAG" },
  { question: "Which analysis determines the 'meaning' of a program?", options: ["Lexical", "Syntax", "Semantic", "Code Gen"], answer: 2, topic: "Semantic Analysis" },
  { question: "Regular expressions are used in which phase?", options: ["Parsing", "Lexical Analysis", "Optimization", "IR Generation"], answer: 1, topic: "Regular Expressions" },
  { question: "Which parser reads input left-to-right with leftmost derivation?", options: ["LR Parser", "LL Parser", "SLR Parser", "LALR Parser"], answer: 1, topic: "LL(1) Parser" },
  { question: "Syntax Directed Translation is associated with?", options: ["Lexical Analysis", "Semantic rules attached to grammar", "Code Optimization", "Register Allocation"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Loop invariant code motion is a type of?", options: ["Peephole Opt", "Loop Optimization", "Dead Code Elimination", "Constant Folding"], answer: 1, topic: "Loop Optimization" },
  { question: "Data flow analysis is used for?", options: ["Token generation", "Type checking", "Optimization opportunities", "Grammar validation"], answer: 2, topic: "Data Flow Analysis" },
  { question: "Register allocation aims to?", options: ["Parse tokens", "Minimize register usage", "Build parse tree", "Generate IR"], answer: 1, topic: "Register Allocation" },
  { question: "An NFA can be converted to a DFA using?", options: ["Thompson's construction", "Subset construction", "Reduction", "Normalization"], answer: 1, topic: "Finite Automata" },
  { question: "The handle in a shift-reduce parser is?", options: ["A terminal", "A production's RHS matching stack top", "The start symbol", "A lookahead"], answer: 1, topic: "Shift Reduce Parser" },
  { question: "Dead code elimination removes?", options: ["All loops", "Unreachable code", "All variables", "Comments"], answer: 1, topic: "Code Optimization" },
  { question: "Which phase assigns addresses to variables?", options: ["Lexical", "Syntax", "Code Generation", "Semantic"], answer: 2, topic: "Code Generation" },
  { question: "A symbol table is primarily used during?", options: ["Only Lexical", "All phases", "Only Optimization", "Only Code Gen"], answer: 1, topic: "Phases of Compiler" },
  { question: "Ambiguous grammar has?", options: ["No parse tree", "Exactly one parse tree", "More than one parse tree", "Only leaves"], answer: 2, topic: "CFG" },
  { question: "Strength reduction replaces?", options: ["Weak ops with strong", "Expensive ops with cheaper", "Variables with constants", "Loops with recursion"], answer: 1, topic: "Code Optimization" },
  { question: "The front end of a compiler includes?", options: ["Code Gen + Opt", "Lexical + Syntax + Semantic", "Only Lexical", "Only Optimization"], answer: 1, topic: "Phases of Compiler" },
  { question: "What does a lexer output?", options: ["Parse tree", "Token stream", "Assembly code", "IR"], answer: 1, topic: "Lexical Analysis" },
  { question: "LL(1) means?", options: ["Left-to-right, Leftmost, 1 lookahead", "Left-to-right, Rightmost, 1 lookahead", "Right scan, Left derivation", "None"], answer: 0, topic: "LL(1) Parser" },
  { question: "Which is NOT a compiler phase?", options: ["Lexical", "Linking", "Semantic", "Optimization"], answer: 1, topic: "Phases of Compiler" },
  { question: "Type checking is done in?", options: ["Lexical", "Syntax", "Semantic", "Code Gen"], answer: 2, topic: "Semantic Analysis" },
  { question: "Basic blocks are used in?", options: ["Lexical Analysis", "Code Optimization", "Parsing", "Linking"], answer: 1, topic: "Basic Blocks" },
];

const ASSESSMENT_2: QuizQuestion[] = [
  { question: "Thompson's construction converts?", options: ["DFA to NFA", "Regex to NFA", "NFA to DFA", "Grammar to PDA"], answer: 1, topic: "Finite Automata" },
  { question: "ε-closure is used in?", options: ["Lexical Analysis", "NFA to DFA conversion", "Code Optimization", "Parsing"], answer: 1, topic: "Finite Automata" },
  { question: "A production A → aB is?", options: ["Left recursive", "Right linear", "Ambiguous", "Null production"], answer: 1, topic: "CFG" },
  { question: "Left factoring eliminates?", options: ["Ambiguity", "Common prefixes", "Left recursion", "Null productions"], answer: 1, topic: "CFG" },
  { question: "FOLLOW(A) contains $ if?", options: ["A is a terminal", "A is the start symbol", "A derives ε", "A is recursive"], answer: 1, topic: "FIRST and FOLLOW" },
  { question: "An SLR parser uses?", options: ["FIRST sets only", "FOLLOW sets for reduce", "Canonical LR items", "No lookahead"], answer: 1, topic: "LR Parser" },
  { question: "LALR stands for?", options: ["Left-right LR", "Look-Ahead LR", "Linear LR", "Lexical LR"], answer: 1, topic: "LR Parser" },
  { question: "Which is more powerful: LALR or SLR?", options: ["SLR", "LALR", "Both equal", "Neither"], answer: 1, topic: "LR Parser" },
  { question: "In SDT, attributes flow from parent to child are?", options: ["Synthesized", "Inherited", "Lexical", "Terminal"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "S-attributed definitions use only?", options: ["Inherited attributes", "Synthesized attributes", "Both", "Neither"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Quadruples have how many fields?", options: ["2", "3", "4", "5"], answer: 2, topic: "Three Address Code" },
  { question: "In a DAG, common subexpressions are?", options: ["Duplicated", "Shared as single node", "Removed", "Ignored"], answer: 1, topic: "DAG" },
  { question: "Copy propagation replaces?", options: ["Constants", "Variables with their assigned values", "Loops", "Functions"], answer: 1, topic: "Code Optimization" },
  { question: "Live variable analysis determines?", options: ["Dead code", "Variables used after a point", "Loop depth", "Parse tree height"], answer: 1, topic: "Data Flow Analysis" },
  { question: "Graph coloring is used for?", options: ["Parsing", "Lexical analysis", "Register allocation", "Optimization"], answer: 2, topic: "Register Allocation" },
  { question: "A basic block has?", options: ["Multiple entry, single exit", "Single entry, single exit", "Multiple entries and exits", "No branches"], answer: 1, topic: "Basic Blocks" },
  { question: "Control flow graph nodes are?", options: ["Tokens", "Basic blocks", "Parse tree nodes", "Registers"], answer: 1, topic: "Code Optimization" },
  { question: "Induction variable elimination optimizes?", options: ["If-else", "Loops", "Functions", "Arrays"], answer: 1, topic: "Loop Optimization" },
  { question: "Available expressions analysis is a?", options: ["Backward analysis", "Forward analysis", "Neither", "Lexical analysis"], answer: 1, topic: "Data Flow Analysis" },
  { question: "Reaching definitions help detect?", options: ["Syntax errors", "Uninitialized variables", "Lexical errors", "Type errors"], answer: 1, topic: "Data Flow Analysis" },
  { question: "A handle is found by?", options: ["Lexer", "Shift-reduce parser", "LL parser", "Optimizer"], answer: 1, topic: "Shift Reduce Parser" },
  { question: "Operator precedence parsing is?", options: ["Top-down", "Bottom-up", "Neither", "Recursive descent"], answer: 1, topic: "Syntax Analysis" },
  { question: "Panic mode recovery is used in?", options: ["Optimization", "Error recovery in parsing", "Lexical analysis", "Code gen"], answer: 1, topic: "Syntax Analysis" },
  { question: "The output of syntax analysis is?", options: ["Token stream", "Parse tree", "Object code", "Symbol table"], answer: 1, topic: "Syntax Analysis" },
  { question: "Backpatching is used in?", options: ["Lexical phase", "Boolean expression code gen", "Register allocation", "Parsing"], answer: 1, topic: "Intermediate Code" },
  { question: "A cross compiler generates code for?", options: ["Same machine", "Different machine", "Virtual machine only", "No machine"], answer: 1, topic: "Phases of Compiler" },
  { question: "Triples differ from quadruples by?", options: ["No result field", "No operator field", "No operand fields", "Extra field"], answer: 0, topic: "Three Address Code" },
  { question: "Common subexpression elimination is?", options: ["Local optimization", "Global optimization", "Machine-dependent", "Lexical"], answer: 1, topic: "Code Optimization" },
  { question: "Loop unrolling is a?", options: ["Code optimization technique", "Parsing technique", "Lexical technique", "Semantic rule"], answer: 0, topic: "Loop Optimization" },
  { question: "Def-use chain links?", options: ["Tokens to grammar", "Definitions to uses", "Blocks to loops", "Registers to memory"], answer: 1, topic: "Data Flow Analysis" },
];

const ASSESSMENT_3: QuizQuestion[] = [
  { question: "Recursive descent parser is?", options: ["Bottom-up", "Top-down", "LR type", "Shift-reduce"], answer: 1, topic: "Syntax Analysis" },
  { question: "FIRST(ε) = ?", options: ["{ε}", "∅", "{$}", "{a}"], answer: 0, topic: "FIRST and FOLLOW" },
  { question: "If FIRST(A) ∩ FIRST(B) ≠ ∅ in A|B, grammar is?", options: ["LL(1)", "Not LL(1)", "LR(1)", "Ambiguous always"], answer: 1, topic: "LL(1) Parser" },
  { question: "Canonical LR is also called?", options: ["SLR", "LALR", "CLR or LR(1)", "LL(1)"], answer: 2, topic: "LR Parser" },
  { question: "Viable prefix is?", options: ["Complete handle", "Prefix of right sentential form on stack", "Token prefix", "Grammar prefix"], answer: 1, topic: "LR Parser" },
  { question: "L-attributed definitions can be evaluated in?", options: ["Any order", "Single left-to-right pass", "Bottom-up only", "Right-to-left only"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Annotated parse tree contains?", options: ["Only tokens", "Attributes at each node", "Assembly code", "Only terminals"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Indirect triples use?", options: ["Pointers to triple table", "Extra result field", "No operators", "Double operands"], answer: 0, topic: "Three Address Code" },
  { question: "Algebraic simplification replaces x*1 with?", options: ["x*0", "x", "1", "0"], answer: 1, topic: "Code Optimization" },
  { question: "Spilling in register allocation means?", options: ["Adding registers", "Storing register values in memory", "Removing dead code", "Optimizing loops"], answer: 1, topic: "Register Allocation" },
  { question: "Dominator tree is used in?", options: ["Lexical analysis", "Loop detection", "Token generation", "Grammar simplification"], answer: 1, topic: "Code Optimization" },
  { question: "Natural loop has?", options: ["No back edge", "A back edge and single entry", "Multiple entries", "No header"], answer: 1, topic: "Loop Optimization" },
  { question: "Reducible flow graph means?", options: ["No loops", "Loops can be identified naturally", "Only one block", "No edges"], answer: 1, topic: "Code Optimization" },
  { question: "Constant propagation replaces variable with?", options: ["Another variable", "Its constant value", "A register", "A loop counter"], answer: 1, topic: "Code Optimization" },
  { question: "Partial redundancy elimination combines?", options: ["CSE and loop-invariant code motion", "Lexical and syntax", "Parsing and codegen", "IR and assembly"], answer: 0, topic: "Code Optimization" },
  { question: "Use-def chain maps?", options: ["Use to its reaching definitions", "Definition to its uses", "Token to type", "Grammar to tree"], answer: 0, topic: "Data Flow Analysis" },
  { question: "GEN and KILL sets are used in?", options: ["Lexical", "Data flow equations", "Parsing", "Register allocation"], answer: 1, topic: "Data Flow Analysis" },
  { question: "Instruction selection maps?", options: ["Tokens to grammar", "IR to machine instructions", "Source to tokens", "Grammar to parse tree"], answer: 1, topic: "Code Generation" },
  { question: "Instruction scheduling minimizes?", options: ["Tokens", "Pipeline stalls", "Parse tree depth", "Symbol table size"], answer: 1, topic: "Code Generation" },
  { question: "Sethi-Ullman numbering optimizes?", options: ["Register usage in expression trees", "Loop iterations", "Grammar size", "Token count"], answer: 0, topic: "Register Allocation" },
  { question: "A finite automaton accepts?", options: ["CFG", "Regular language", "CSG", "Recursively enumerable language"], answer: 1, topic: "Finite Automata" },
  { question: "Minimization of DFA reduces?", options: ["Transitions", "States", "Alphabets", "All of above"], answer: 1, topic: "Finite Automata" },
  { question: "Pumping lemma is used to prove?", options: ["Language is regular", "Language is NOT regular", "Grammar is ambiguous", "Parser is correct"], answer: 1, topic: "Regular Expressions" },
  { question: "(a|b)* matches?", options: ["Only 'a'", "Only 'b'", "Any string of a's and b's", "Empty string only"], answer: 2, topic: "Regular Expressions" },
  { question: "Kleene closure means?", options: ["One or more", "Zero or more", "Exactly one", "None"], answer: 1, topic: "Regular Expressions" },
  { question: "A sentential form is derived from?", options: ["Tokens", "Start symbol", "Assembly", "Registers"], answer: 1, topic: "CFG" },
  { question: "A derivation tree is also called?", options: ["Token tree", "Parse tree", "AST", "DAG"], answer: 1, topic: "CFG" },
  { question: "Rightmost derivation in reverse is used by?", options: ["LL parser", "LR parser", "Lexer", "Optimizer"], answer: 1, topic: "LR Parser" },
  { question: "Symbol table stores?", options: ["Only types", "Names, types, scopes, addresses", "Only addresses", "Only names"], answer: 1, topic: "Semantic Analysis" },
  { question: "Scope resolution happens in?", options: ["Lexical", "Semantic analysis", "Code gen", "Optimization"], answer: 1, topic: "Semantic Analysis" },
];

const ASSESSMENT_4: QuizQuestion[] = [
  { question: "What is the role of a scanner?", options: ["Build parse tree", "Tokenize input", "Generate IR", "Optimize code"], answer: 1, topic: "Lexical Analysis" },
  { question: "Maximal munch rule is used in?", options: ["Parsing", "Lexical analysis", "Optimization", "Code gen"], answer: 1, topic: "Lexical Analysis" },
  { question: "LEX is a tool for?", options: ["Parsing", "Lexical analyzer generation", "Optimization", "Assembly"], answer: 1, topic: "Lexical Analysis" },
  { question: "YACC stands for?", options: ["Yet Another Compiler Compiler", "You Are Creating Code", "Yet Another Code Creator", "Yes All Compilers Compile"], answer: 0, topic: "Syntax Analysis" },
  { question: "Predictive parser uses?", options: ["Backtracking", "Lookahead without backtracking", "Shift-reduce", "No lookahead"], answer: 1, topic: "LL(1) Parser" },
  { question: "First(aα) = ?", options: ["{a}", "First(α)", "{ε}", "Follow(A)"], answer: 0, topic: "FIRST and FOLLOW" },
  { question: "If A → ε, then FIRST(A) contains?", options: ["{$}", "{ε}", "∅", "{a}"], answer: 1, topic: "FIRST and FOLLOW" },
  { question: "LL(1) parsing table has conflict when?", options: ["Table is empty", "Cell has multiple entries", "No start symbol", "Grammar is left recursive"], answer: 1, topic: "LL(1) Parser" },
  { question: "Left recursion causes?", options: ["Finite loop", "Infinite loop in top-down parsing", "No effect", "Better performance"], answer: 1, topic: "Syntax Analysis" },
  { question: "An augmented grammar adds?", options: ["New terminals", "S' → S production", "Extra tokens", "More operators"], answer: 1, topic: "LR Parser" },
  { question: "LR(0) item A → α.β means?", options: ["α has been seen, β expected", "β has been seen, α expected", "Both seen", "Neither seen"], answer: 0, topic: "LR Parser" },
  { question: "Reduce-reduce conflict means?", options: ["Two shifts possible", "Two reductions possible", "Shift and reduce both possible", "No action possible"], answer: 1, topic: "LR Parser" },
  { question: "Shift-reduce conflict means?", options: ["Two reductions", "Shift and reduce both possible", "Two shifts", "Error state"], answer: 1, topic: "Shift Reduce Parser" },
  { question: "Inherited attributes flow?", options: ["Bottom to top", "Top to bottom or left to right", "Right to left only", "Not at all"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Synthesized attributes flow?", options: ["Top to bottom", "Bottom to top", "Left to right", "Nowhere"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Static type checking happens at?", options: ["Runtime", "Compile time", "Link time", "Load time"], answer: 1, topic: "Semantic Analysis" },
  { question: "Coercion is?", options: ["Explicit type conversion", "Implicit type conversion", "Error detection", "Optimization"], answer: 1, topic: "Semantic Analysis" },
  { question: "Boolean short-circuit evaluation skips?", options: ["All operands", "Unnecessary operand evaluation", "Function calls", "Assignments"], answer: 1, topic: "Intermediate Code" },
  { question: "Switch statement IR commonly uses?", options: ["Jump table", "Recursion", "Stack", "Queue"], answer: 0, topic: "Intermediate Code" },
  { question: "SSA form means?", options: ["Single Source Assignment", "Static Single Assignment", "Simple Syntax Analysis", "Structured Sequential Analysis"], answer: 1, topic: "Code Optimization" },
  { question: "Phi function is used in?", options: ["Lexical analysis", "SSA form at merge points", "Parsing", "Tokenizing"], answer: 1, topic: "Code Optimization" },
  { question: "Tail call optimization eliminates?", options: ["Recursion overhead", "All function calls", "Loops", "Variables"], answer: 0, topic: "Code Optimization" },
  { question: "Function inlining replaces call with?", options: ["Another call", "Function body", "A loop", "A variable"], answer: 1, topic: "Code Optimization" },
  { question: "What is peephole optimization window size?", options: ["Entire program", "A small set of instructions", "One instruction", "Entire function"], answer: 1, topic: "Peephole Optimization" },
  { question: "Redundant load elimination is?", options: ["Peephole optimization", "Loop optimization", "Global optimization", "Lexical optimization"], answer: 0, topic: "Peephole Optimization" },
  { question: "Dependency graph determines?", options: ["Token order", "Evaluation order of attributes", "Register allocation", "Loop nesting"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Type expression int → int represents?", options: ["Integer variable", "Function taking int returning int", "Array of ints", "Pointer to int"], answer: 1, topic: "Semantic Analysis" },
  { question: "Widening converts?", options: ["Larger to smaller type", "Smaller to larger type", "Same type", "No conversion"], answer: 1, topic: "Semantic Analysis" },
  { question: "Activation record stores?", options: ["Tokens", "Function call info (locals, return addr)", "Parse tree", "Grammar"], answer: 1, topic: "Code Generation" },
  { question: "Caller-save registers are saved by?", options: ["Callee", "Caller before call", "OS", "Linker"], answer: 1, topic: "Register Allocation" },
];

const ASSESSMENT_5: QuizQuestion[] = [
  { question: "Transition diagram is used for?", options: ["Parsing", "Implementing lexer", "Optimization", "Linking"], answer: 1, topic: "Lexical Analysis" },
  { question: "Token has which components?", options: ["Name and value", "Token name, attribute value", "Only name", "Only value"], answer: 1, topic: "Lexical Analysis" },
  { question: "Lookahead operator '/' in LEX means?", options: ["Division", "Match but don't consume following pattern", "Comment", "Or operator"], answer: 1, topic: "Regular Expressions" },
  { question: "r+ in regex means?", options: ["Zero or more r", "One or more r", "Exactly one r", "Optional r"], answer: 1, topic: "Regular Expressions" },
  { question: "A pushdown automaton is used for?", options: ["Regular languages", "Context-free languages", "Context-sensitive", "Unrestricted"], answer: 1, topic: "Syntax Analysis" },
  { question: "Bottom-up parsing builds tree from?", options: ["Root to leaves", "Leaves to root", "Left to right", "Right to left"], answer: 1, topic: "Syntax Analysis" },
  { question: "Dangling else is resolved by?", options: ["Left factoring", "Matching else with nearest if", "Left recursion removal", "Optimization"], answer: 1, topic: "CFG" },
  { question: "ε-production is A → ?", options: ["A → a", "A → AB", "A → ε", "A → aA"], answer: 2, topic: "CFG" },
  { question: "Chomsky Normal Form requires productions of form?", options: ["A → BC or A → a", "A → aB", "A → aBc", "Any form"], answer: 0, topic: "CFG" },
  { question: "Operator grammar has no production with?", options: ["Terminals", "Two adjacent non-terminals", "Operators", "ε"], answer: 1, topic: "Syntax Analysis" },
  { question: "In FOLLOW computation, $ is added to?", options: ["Every non-terminal", "Start symbol only", "Every terminal", "No symbol"], answer: 1, topic: "FIRST and FOLLOW" },
  { question: "Predictive parsing table is indexed by?", options: ["Non-terminal and terminal", "Two terminals", "Two non-terminals", "Terminal only"], answer: 0, topic: "LL(1) Parser" },
  { question: "GOTO function in LR parsing takes?", options: ["State and terminal", "State and non-terminal", "Two states", "Terminal and non-terminal"], answer: 1, topic: "LR Parser" },
  { question: "ACTION table entries can be?", options: ["Shift, Reduce, Accept, Error", "Only Shift", "Only Reduce", "Shift and Accept only"], answer: 0, topic: "LR Parser" },
  { question: "Parser generator YACC produces?", options: ["Lexer", "LALR(1) parser", "LL(1) parser", "Recursive descent parser"], answer: 1, topic: "Syntax Analysis" },
  { question: "Marker non-terminal is used for?", options: ["Optimization", "Embedded actions in SDT", "Lexical analysis", "Error recovery"], answer: 1, topic: "Syntax Directed Translation" },
  { question: "Type synthesis computes type from?", options: ["Parent node", "Children node types", "Sibling nodes", "Root only"], answer: 1, topic: "Semantic Analysis" },
  { question: "Polymorphic function works with?", options: ["Only one type", "Multiple types", "No types", "Only integers"], answer: 1, topic: "Semantic Analysis" },
  { question: "Array access a[i] IR may use?", options: ["Base + i * width", "Just i", "Base only", "Width only"], answer: 0, topic: "Intermediate Code" },
  { question: "Procedure calls in IR use?", options: ["param and call instructions", "Only goto", "Only labels", "No special instruction"], answer: 0, topic: "Intermediate Code" },
  { question: "Code hoisting moves?", options: ["Code out of loops", "Common code to earlier point", "Code to end", "Nothing"], answer: 1, topic: "Code Optimization" },
  { question: "Interprocedural optimization analyzes?", options: ["Single function", "Across function boundaries", "Only loops", "Only blocks"], answer: 1, topic: "Code Optimization" },
  { question: "Software pipelining overlaps?", options: ["Functions", "Loop iterations", "Blocks", "Files"], answer: 1, topic: "Loop Optimization" },
  { question: "Busy expressions analysis is?", options: ["Forward", "Backward", "Neither", "Lexical"], answer: 1, topic: "Data Flow Analysis" },
  { question: "Liveness analysis is?", options: ["Forward", "Backward", "Neither", "Top-down"], answer: 1, topic: "Data Flow Analysis" },
  { question: "Interference graph edge means?", options: ["Two variables are used together", "Two variables are live simultaneously", "Sequential definitions", "No relation"], answer: 1, topic: "Register Allocation" },
  { question: "k-coloring of interference graph uses?", options: ["k tokens", "k registers", "k optimizations", "k blocks"], answer: 1, topic: "Register Allocation" },
  { question: "Branch prediction is part of?", options: ["Lexical analysis", "Machine-dependent optimization", "Parsing", "Semantic analysis"], answer: 1, topic: "Code Optimization" },
  { question: "Just-in-time compilation happens at?", options: ["Compile time", "Runtime", "Link time", "Load time"], answer: 1, topic: "Phases of Compiler" },
  { question: "Intermediate representation should be?", options: ["Machine specific", "Machine independent", "Language specific", "Platform locked"], answer: 1, topic: "Intermediate Code" },
];

export const ASSESSMENTS: QuizQuestion[][] = [
  ASSESSMENT_1,
  ASSESSMENT_2,
  ASSESSMENT_3,
  ASSESSMENT_4,
  ASSESSMENT_5,
];

export function getAssessmentQuestions(idx: number): QuizQuestion[] {
  const qs = [...ASSESSMENTS[idx]];
  for (let i = qs.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [qs[i], qs[j]] = [qs[j], qs[i]];
  }
  return qs;
}
